# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Ye Wang (Eric)
tagline:             Applied Statistician
url:                 http://ericyewang.github.io
paginate:            1
baseurl:             http://ericyewang.github.io

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Ye Wang
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/poole/poole

# This is the list of pages to include in the header of the website.
pages_list:
  CV: '/cv/'
  Blog: '/archive/'
  Publications: '/publications/'
  Teaching: '/teaching/'
  Code: '/code/'
  Contact: '/contact/'
